/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "basalt": {
    "base": "basalt",
    "width": 2256,
    "height": 1504,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "boat": {
    "base": "boat",
    "width": 3840,
    "height": 2560,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coastline": {
    "base": "coastline",
    "width": 3840,
    "height": 2609,
    "fallbackWidth": 1920,
    "fallbackHeight": 1305,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 3840,
    "height": 2563,
    "fallbackWidth": 1920,
    "fallbackHeight": 1282,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "e-bike": {
    "base": "e-bike",
    "width": 3264,
    "height": 1840,
    "fallbackWidth": 800,
    "fallbackHeight": 451,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 2256,
    "height": 1504,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 2048,
    "height": 1536,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 3264,
    "height": 1840,
    "fallbackWidth": 1920,
    "fallbackHeight": 1082,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hiking": {
    "base": "hiking",
    "width": 3840,
    "height": 2842,
    "fallbackWidth": 800,
    "fallbackHeight": 592,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hydrangea": {
    "base": "hydrangea",
    "width": 3840,
    "height": 2560,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "lagoa-do-fogo": {
    "base": "lagoa-do-fogo",
    "width": 3840,
    "height": 2410,
    "fallbackWidth": 1920,
    "fallbackHeight": 1205,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 3264,
    "height": 1840,
    "fallbackWidth": 1920,
    "fallbackHeight": 1082,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "photography": {
    "base": "photography",
    "width": 3264,
    "height": 1840,
    "fallbackWidth": 1920,
    "fallbackHeight": 1082,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "ponta-delgada": {
    "base": "ponta-delgada",
    "width": 3840,
    "height": 2292,
    "fallbackWidth": 800,
    "fallbackHeight": 478,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 3840,
    "height": 2563,
    "fallbackWidth": 800,
    "fallbackHeight": 534,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "sete-cidades": {
    "base": "sete-cidades",
    "width": 3840,
    "height": 2563,
    "fallbackWidth": 1920,
    "fallbackHeight": 1282,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 3840,
    "height": 2292,
    "fallbackWidth": 800,
    "fallbackHeight": 478,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "waterfront": {
    "base": "waterfront",
    "width": 2132,
    "height": 1416,
    "fallbackWidth": 1920,
    "fallbackHeight": 1275,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "whale": {
    "base": "whale",
    "width": 3840,
    "height": 2560,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
